var colors = [ "ALICEBLUE", "DARKOLIVEGREEN", "INDIGO", "MEDIUMPURPLE", "PURPLE", "ANTIQUEWHITE", "DARKORANGE", "IVORY", "MEDIUMSEAGREEN", "RED", "AQUA", "DARKORCHID", "KHAKI", "MEDIUMSLATEBLUE", "ROSYBROWN", "AQUAMARINE", "DARKRED", "LAVENDER", "MEDIUMSPRINGGREEN", "ROYALBLUE", "AZURE", "DARKSALMON", "LAVENDERBLUSH", "MEDIUMTURQUOISE", "SADDLEBROWN", "BEIGE", "DARKSEAGREEN", "LAWNGREEN", "MEDIUMVIOLETRED", "SALMON", "BISQUE", "DARKSLATEBLUE", "LEMONCHIFFON", "MIDNIGHTBLUE", "SANDYBROWN", "BLACK", "DARKSLATEGRAY", "LIGHTBLUE", "MINTCREAM", "SEAGREEN", "BLANCHEDALMOND", "DARKTURQUOISE", "LIGHTCORAL", "MISTYROSE", "SEASHELL", "BLUE", "DARKVIOLET", "LIGHTCYAN", "MOCCASIN", "SIENNA", "BLUEVIOLET", "DEEPPINK", "LIGHTGOLDENRODYELLOW", "NAVAJOWHITE", "SILVER", "BROWN", "DEEPSKYBLUE", "LIGHTGRAY", "NAVY", "SKYBLUE", "BURLYWOOD", "DIMGRAY", "LIGHTGREEN", "OLDLACE", "SLATEBLUE", "CADETBLUE", "DODGERBLUE", "LIGHTPINK", "OLIVE", "SLATEGRAY", "CHARTREUSE", "FIREBRICK", "LIGHTSALMON", "OLIVEDRAB", "SNOW", "CHOCOLATE", "FLORALWHITE", "LIGHTSEAGREEN", "ORANGE", "SPRINGGREEN", "CORAL", "FORESTGREEN", "LIGHTSKYBLUE", "ORANGERED", "STEELBLUE", "CORNFLOWERBLUE", "FUCHSIA", "LIGHTSLATEGRAY", "ORCHID", "TAN", "CORNSILK", "GAINSBORO", "LIGHTSTEELBLUE", "PALEGOLDENROD", "TEAL", "CRIMSON", "GHOSTWHITE", "LIGHTYELLOW", "PALEGREEN", "THISTLE", "CYAN", "GOLD", "LIME", "PALETURQUOISE", "TOMATO", "DARKBLUE", "GOLDENROD", "LIMEGREEN", "PALEVIOLETRED", "TURQUOISE", "DARKCYAN", "GRAY", "LINEN", "PAPAYAWHIP", "VIOLET", "DARKGOLDENROD", "GREEN", "MAGENTA", "PEACHPUFF", "WHEAT", "DARKGRAY", "GREENYELLOW", "MAROON", "PERU", "WHITE", "DARKGREEN", "HONEYDEW", "MEDIUMAQUAMARINE", "PINK", "WHITESMOKE", "DARKKHAKI", "HOTPINK", "MEDIUMBLUE", "PLUM", "YELLOW", "DARKMAGENTA", "INDIANRED", "MEDIUMORCHID", "POWDERBLUE", "YELLOWGREEN" ];

var inputColor = '';

$(document).keydown(function(event) {
	if (/[a-z]/i.test(String.fromCharCode(event.keyCode))) {
		inputColor += String.fromCharCode(event.keyCode);
	}

	if (colors.indexOf(inputColor) >= 0) {
		console.log("Background color : ", inputColor);
		$(document.body).css("background-color", inputColor);
		inputColor = '';
	}
});

function resetBackgroundColor(color = "WHITE") {
	$(document.body).css("background-color", color);
	inputColor = '';
}